# Generated by Django 3.2.23 on 2024-03-11 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(blank=True)),
                ('date_joined', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(blank=True, max_length=50, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('build', models.CharField(blank=True, max_length=50, null=True)),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('political_conviction', models.CharField(blank=True, max_length=100, null=True)),
                ('kids', models.BooleanField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile_user', to='authentication.user')),
            ],
        ),
    ]
